name: user_hub_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get_it: ^8.2.0
  go_router: ^16.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/icono.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: "assets/images/user_form_splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
